#!/bin/bash
set -e

# Source library functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
source "${SCRIPT_DIR}/setup-lib.sh"

# ═══════════════════════════════════════════════
#  Not-ify — Own Your Sound
#  Container-side setup: receives pre-configured
#  paths from bootstrap.sh and handles compose
#  generation, config writing, and startup.
# ═══════════════════════════════════════════════

# Parse args
INSTALL_DIR="" MUSIC_DIR="" PORT="" API_KEY="" ENABLE_VPN="n" ENABLE_CLAMAV="n"
for arg in "$@"; do
  case "$arg" in
    --install-dir=*) INSTALL_DIR="${arg#*=}" ;;
    --music-dir=*)   MUSIC_DIR="${arg#*=}" ;;
    --port=*)        PORT="${arg#*=}" ;;
    --api-key=*)     API_KEY="${arg#*=}" ;;
    --vpn=*)         ENABLE_VPN="${arg#*=}" ;;
    --clamav=*)      ENABLE_CLAMAV="${arg#*=}" ;;
    --help|-h)
      echo "Not-ify setup (container-side)"
      echo ""
      echo "Usage: docker run ... ghcr.io/illtrick/not-ify:latest setup [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --install-dir=PATH  Install directory on host (required)"
      echo "  --music-dir=PATH    Music library path on host (required)"
      echo "  --port=PORT         Web UI port (default: 3000)"
      echo "  --api-key=KEY       slskd API key (auto-generated if omitted)"
      echo ""
      echo "Tip: Run bootstrap.sh on the host instead of calling this directly."
      echo "  curl -sL https://raw.githubusercontent.com/illtrick/not-ify/main/scripts/bootstrap.sh | bash"
      exit 0 ;;
  esac
done

# Use env vars as fallback
INSTALL_DIR="${INSTALL_DIR:-$NOTIFY_INSTALL_DIR}"
MUSIC_DIR="${MUSIC_DIR:-$NOTIFY_MUSIC_DIR}"
PORT="${PORT:-${NOTIFY_PORT:-3000}}"
API_KEY="${API_KEY:-${NOTIFY_SLSKD_API_KEY:-$(generate_uuid)}}"
ENABLE_VPN="${ENABLE_VPN:-${NOTIFY_ENABLE_VPN:-n}}"
ENABLE_CLAMAV="${ENABLE_CLAMAV:-${NOTIFY_ENABLE_CLAMAV:-n}}"

HOST_INSTALL="/host/install"

if [ -z "$INSTALL_DIR" ] || [ -z "$MUSIC_DIR" ]; then
  error "Missing required arguments --install-dir and --music-dir."
  echo ""
  echo "  Run bootstrap.sh on the host for the full interactive setup:"
  echo "    curl -sL https://raw.githubusercontent.com/illtrick/not-ify/main/scripts/bootstrap.sh | bash"
  exit 1
fi

# Verify Docker socket is available
if [ ! -S /var/run/docker.sock ]; then
  error "Docker socket not mounted."
  echo "  Run with: -v /var/run/docker.sock:/var/run/docker.sock"
  exit 1
fi

# Verify install dir is mounted
if [ ! -d "$HOST_INSTALL" ]; then
  error "Install directory not mounted at $HOST_INSTALL"
  echo "  Run with: -v ${INSTALL_DIR}:/host/install"
  exit 1
fi

BUNDLED_VERSION=$(get_bundled_version)
info "Not-ify v${BUNDLED_VERSION}"
echo ""

# Check for existing installation
if [ -f "${HOST_INSTALL}/docker-compose.yml" ] && [ -d "${HOST_INSTALL}/config" ]; then
  warn "Existing installation found."
  RUNNING_VERSION=$(get_running_version "$PORT")
  [ -z "$RUNNING_VERSION" ] && RUNNING_VERSION="not running"
  info "Running: v${RUNNING_VERSION}  →  Available: v${BUNDLED_VERSION}"
  echo ""
  info "Updating containers (existing data preserved)..."
  cd "${HOST_INSTALL}"
  docker compose pull 2>&1 | sed 's/^/  /' || true
  docker compose up -d 2>&1 | sed 's/^/  /'
  success "Updated to v${BUNDLED_VERSION}"
  exit 0
fi

info "Generating configuration..."

# Write single .env file (all config in one place for simple docker compose commands)
cat > "${HOST_INSTALL}/.env" << EOF
# Not-ify configuration — generated by setup
PORT=${PORT}
NODE_ENV=production
LOG_LEVEL=info
DLNA_ENABLED=true
MUSIC_DIR=${MUSIC_DIR}
CONFIG_DIR=${INSTALL_DIR}/config
SLSKD_API_KEY=${API_KEY}
SLSKD_DOWNLOADS_DIR=${INSTALL_DIR}/slskd-downloads
EOF

# Write slskd config with auto-generated Soulseek credentials
# These are placeholder credentials so slskd starts cleanly.
# Users update with their real account in the Not-ify Settings UI.
mkdir -p "${HOST_INSTALL}/slskd"
SLSK_AUTO_USER="notifier-$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
SLSK_AUTO_PASS="$(head -c 12 /dev/urandom | od -An -tx1 | tr -d ' \n')"
cat > "${HOST_INSTALL}/slskd/slskd.yml" << EOF
soulseek:
  username: ${SLSK_AUTO_USER}
  password: ${SLSK_AUTO_PASS}

web:
  authentication:
    api_keys:
      ${API_KEY}:
        role: administrator

options:
  listen_port: 50300
EOF

# Copy compose template and enable optional services
cp "${SCRIPT_DIR}/docker-compose.template.yml" "${HOST_INSTALL}/docker-compose.yml"

# Enable VPN (Gluetun) if requested
if [ "$ENABLE_VPN" = "y" ]; then
  sed -i 's/^#VPN#//' "${HOST_INSTALL}/docker-compose.yml"
  # Add VPN proxy env to not-ify
  cat >> "${HOST_INSTALL}/.env" << EOF
VPN_PROXY=http://localhost:8888
GLUETUN_CONTROL_URL=http://localhost:8000
EOF
fi

# Enable ClamAV if requested
if [ "$ENABLE_CLAMAV" = "y" ]; then
  sed -i 's/^#CLAM#//' "${HOST_INSTALL}/docker-compose.yml"
  cat >> "${HOST_INSTALL}/.env" << EOF
CLAM_ENABLED=true
CLAM_HOST=localhost
CLAM_PORT=3310
EOF
fi

success "Configuration written"

# Start containers
info "Starting services..."
cd "${HOST_INSTALL}"
docker compose up -d 2>&1 | sed 's/^/  /'

echo ""

# Health checks — build list of expected containers
CONTAINERS="not-ify slskd watchtower"
[ "$ENABLE_VPN" = "y" ] && CONTAINERS="$CONTAINERS gluetun"
[ "$ENABLE_CLAMAV" = "y" ] && CONTAINERS="$CONTAINERS clamav"

for container in $CONTAINERS; do
  if wait_healthy "$container" 60; then
    version_suffix=""
    if [ "$container" = "not-ify" ]; then
      running_ver=$(get_running_version "$PORT")
      [ -n "$running_ver" ] && version_suffix=" (v${running_ver})"
    fi
    success "${container}${version_suffix}"
  else
    warn "${container} — may still be starting"
    docker logs "$container" --tail 3 2>&1 | sed 's/^/    /' || true
  fi
done
