#!/bin/bash
set -e

# Source library functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
source "${SCRIPT_DIR}/setup-lib.sh"

# ═══════════════════════════════════════════════
#  Not-ify — Own Your Sound
#  Container-side setup: receives pre-configured
#  paths from bootstrap.sh and handles compose
#  generation, config writing, and startup.
# ═══════════════════════════════════════════════

# Parse args
INSTALL_DIR="" MUSIC_DIR="" PORT="" API_KEY="" ENABLE_VPN="n" ENABLE_CLAMAV="n"
for arg in "$@"; do
  case "$arg" in
    --install-dir=*) INSTALL_DIR="${arg#*=}" ;;
    --music-dir=*)   MUSIC_DIR="${arg#*=}" ;;
    --port=*)        PORT="${arg#*=}" ;;
    --api-key=*)     API_KEY="${arg#*=}" ;;
    --vpn=*)         ENABLE_VPN="${arg#*=}" ;;
    --clamav=*)      ENABLE_CLAMAV="${arg#*=}" ;;
    --help|-h)
      echo "Not-ify setup (container-side)"
      echo ""
      echo "Usage: docker run ... ghcr.io/illtrick/not-ify:latest setup [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --install-dir=PATH  Install directory on host (required)"
      echo "  --music-dir=PATH    Music library path on host (required)"
      echo "  --port=PORT         Web UI port (default: 3000)"
      echo "  --api-key=KEY       slskd API key (auto-generated if omitted)"
      echo ""
      echo "Tip: Run bootstrap.sh on the host instead of calling this directly."
      echo "  curl -sL https://raw.githubusercontent.com/illtrick/not-ify/main/scripts/bootstrap.sh | bash"
      exit 0 ;;
  esac
done

# Use env vars as fallback
INSTALL_DIR="${INSTALL_DIR:-$NOTIFY_INSTALL_DIR}"
MUSIC_DIR="${MUSIC_DIR:-$NOTIFY_MUSIC_DIR}"
PORT="${PORT:-${NOTIFY_PORT:-3000}}"
API_KEY="${API_KEY:-${NOTIFY_SLSKD_API_KEY:-$(generate_uuid)}}"
ENABLE_VPN="${ENABLE_VPN:-${NOTIFY_ENABLE_VPN:-n}}"
ENABLE_CLAMAV="${ENABLE_CLAMAV:-${NOTIFY_ENABLE_CLAMAV:-n}}"

HOST_INSTALL="/host/install"

if [ -z "$INSTALL_DIR" ] || [ -z "$MUSIC_DIR" ]; then
  error "Missing required arguments --install-dir and --music-dir."
  echo ""
  echo "  Run bootstrap.sh on the host for the full interactive setup:"
  echo "    curl -sL https://raw.githubusercontent.com/illtrick/not-ify/main/scripts/bootstrap.sh | bash"
  exit 1
fi

# Verify Docker socket is available
if [ ! -S /var/run/docker.sock ]; then
  error "Docker socket not mounted."
  echo "  Run with: -v /var/run/docker.sock:/var/run/docker.sock"
  exit 1
fi

# Verify install dir is mounted
if [ ! -d "$HOST_INSTALL" ]; then
  error "Install directory not mounted at $HOST_INSTALL"
  echo "  Run with: -v ${INSTALL_DIR}:/host/install"
  exit 1
fi

BUNDLED_VERSION=$(get_bundled_version)
info "Not-ify v${BUNDLED_VERSION}"
echo ""

# Check for existing installation
if [ -f "${HOST_INSTALL}/docker-compose.yml" ] && [ -d "${HOST_INSTALL}/config" ]; then
  warn "Existing installation found."
  RUNNING_VERSION=$(get_running_version "$PORT")
  [ -z "$RUNNING_VERSION" ] && RUNNING_VERSION="not running"
  info "Running: v${RUNNING_VERSION}  →  Available: v${BUNDLED_VERSION}"
  echo ""
  info "Updating containers (existing data preserved)..."
  cd "${HOST_INSTALL}"
  docker compose pull 2>&1 | sed 's/^/  /' || true
  docker compose up -d 2>&1 | sed 's/^/  /'
  success "Updated to v${BUNDLED_VERSION}"
  exit 0
fi

info "Generating configuration..."

# Write single .env file (all config in one place for simple docker compose commands)
# slskd reads env vars directly — no config file needed (avoids slskd overwriting it)
SLSK_AUTO_USER="notifier-$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
SLSK_AUTO_PASS="$(head -c 12 /dev/urandom | od -An -tx1 | tr -d ' \n')"

cat > "${HOST_INSTALL}/.env" << EOF
# Not-ify configuration — generated by setup
PORT=${PORT}
NODE_ENV=production
LOG_LEVEL=info
DLNA_ENABLED=true
MUSIC_DIR=${MUSIC_DIR}
CONFIG_DIR=${INSTALL_DIR}/config
SLSKD_API_KEY=${API_KEY}
SLSKD_DOWNLOADS_DIR=${INSTALL_DIR}/slskd-downloads
INSTALL_DIR=${INSTALL_DIR}

# Soulseek (slskd) — placeholder creds, update in Settings UI
SLSKD_SLSK_USERNAME=${SLSK_AUTO_USER}
SLSKD_SLSK_PASSWORD=${SLSK_AUTO_PASS}
EOF

# Create slskd data dir and write API key config
# NOTE: slskd env vars work for username/password but NOT for API keys.
# API keys must be in the config file. slskd overwrites the config on first boot,
# so we write it AFTER starting containers and then restart slskd (see below).
mkdir -p "${HOST_INSTALL}/slskd"

# Copy compose template and enable optional services
cp "${SCRIPT_DIR}/docker-compose.template.yml" "${HOST_INSTALL}/docker-compose.yml"

# Enable VPN (Gluetun) if requested
if [ "$ENABLE_VPN" = "y" ]; then
  sed -i 's/^#VPN#//' "${HOST_INSTALL}/docker-compose.yml"
  # Add VPN + gluetun env vars
  # Use credentials from bootstrap wizard if provided, otherwise empty (configured in Settings UI)
  vpn_provider="${NOTIFY_VPN_PROVIDER:-private internet access}"
  vpn_username="${NOTIFY_VPN_USERNAME:-}"
  vpn_password="${NOTIFY_VPN_PASSWORD:-}"
  vpn_region="${NOTIFY_VPN_REGION:-US East}"
  cat >> "${HOST_INSTALL}/.env" << EOF

# VPN (Gluetun)
VPN_PROXY=http://localhost:8888
GLUETUN_CONTROL_URL=http://localhost:8000
VPN_PROVIDER=${vpn_provider}
VPN_USERNAME=${vpn_username}
VPN_PASSWORD=${vpn_password}
VPN_REGION=${vpn_region}
EOF
fi

# Enable ClamAV if requested
if [ "$ENABLE_CLAMAV" = "y" ]; then
  sed -i 's/^#CLAM#//' "${HOST_INSTALL}/docker-compose.yml"
  cat >> "${HOST_INSTALL}/.env" << EOF
CLAM_ENABLED=true
CLAM_HOST=localhost
CLAM_PORT=3310
EOF
fi

success "Configuration written"

# Start containers (suppress verbose Docker output)
info "Starting services..."
cd "${HOST_INSTALL}"
docker compose up -d > /dev/null 2>&1

# Build list of expected containers
CONTAINERS="not-ify slskd watchtower"
[ "$ENABLE_VPN" = "y" ] && CONTAINERS="$CONTAINERS gluetun"
[ "$ENABLE_CLAMAV" = "y" ] && CONTAINERS="$CONTAINERS clamav"
TOTAL=$(echo "$CONTAINERS" | wc -w)

# Configure slskd API key (wait for slskd to be running, not a fixed sleep)
printf "\r\033[K  ${CYAN}▸${NC} Configuring services... [1/${TOTAL}]"
slskd_ready=0
for i in $(seq 1 15); do
  if docker inspect --format='{{.State.Running}}' slskd 2>/dev/null | grep -q true; then
    slskd_ready=1; break
  fi
  sleep 1
done
if [ "$slskd_ready" = "1" ]; then
  docker exec slskd sh -c "cat > /app/slskd.yml << SLSKDEOF
web:
  authentication:
    api_keys:
      notify:
        key: ${API_KEY}
        role: administrator
SLSKDEOF" 2>/dev/null || true
  docker restart slskd > /dev/null 2>&1 || true
fi

# Health checks with progress counter
DONE=0
for container in $CONTAINERS; do
  DONE=$((DONE + 1))
  printf "\r\033[K  ${CYAN}▸${NC} Starting services... [${DONE}/${TOTAL}] %s" "$container"
  if wait_healthy "$container" 30; then
    version_suffix=""
    if [ "$container" = "not-ify" ]; then
      running_ver=$(get_running_version "$PORT")
      [ -n "$running_ver" ] && version_suffix=" (v${running_ver})"
    fi
    printf "\r\033[K  ${GREEN}✓${NC} %s\n" "${container}${version_suffix}"
  else
    # Show helpful estimates for slow-starting services
    hint=""
    [ "$container" = "clamav" ] && hint=" (usually 2-3 min)"
    [ "$container" = "slskd" ] && hint=" (usually 10-30s)"
    printf "\r\033[K  ${YELLOW}!${NC} %s\n" "${container} — may still be starting${hint}"
  fi
done
